---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 老方.
--- DateTime: 2023/4/30 20:39
---

if(redis.call('get',KEYS[1])==ARGV[1]) then
    return redis.call('del',KEYS[1])
end
return 0